### ISSUE TITLE
Error on Server Start

### ISSUE THREAD

**Issue by AstoriaWinters** [The-Fireplace-Minecraft-Mods/Home-Camp#11]
**Describe the bug**
I am trying to have this mod on my server. It keeps giving me errors and failing to start, it seems to be an issue with not being able to read the config? From what I can gather it is an issue in trying to change the "PlayerManager" 

I did not have this issue with the 1.17.1 versions of the mods. So it is something that was changed for 1.18.

**To Reproduce**
Install Fireplace Lib + Home Camp + Essential Commands (0.17.1-mc1.18-rc3 ) *OR* Origins (1.3.0)

**Logs/Screenshots/Videos**

https://gist.github.com/AstoriaWinters/da9e8211c154fca6634233c368a4f1dd

**Versions (please complete the following information, do *NOT* say "latest"):**
 - Minecraft: 1.18
 - Mod Version: 2.2.1+1.18
 - Fabric API: Fabric API 0.44.0

**Comment by The-Fireplace** [comment]
I've started looking in to it. Still not sure why it's happening yet.

**Comment by Jurklein** [comment]
Happening to me as well.

```
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [homecamp.mixins.json:PlayerManagerMixin from mod homecamp] from phase [DEFAULT] in config [homecamp.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 33 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Unexpecteded NullPointerException whilst transforming the mixin class: [INJECT Applicator Phase -> homecamp.mixins.json:PlayerManagerMixin from mod homecamp -> Apply Injections -> PreInject -> homecamp.mixins.json:PlayerManagerMixin from mod homecamp->@Inject::extinguishCampfireAfterSpawning(Lnet/minecraft/class_3222;ZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Lnet/minecraft/class_2338;FZLnet/minecraft/class_3218;)V]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1394)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 33 more
Caused by: java.lang.NullPointerException: Cannot read field "desc" because "frame[varInsn.var]" is null

```

**Comment by milkev** [comment]
getting this bug on fabric 1.19.2. this is my modlist and log if anyone wants. it looks like the playermanager mixin is crashing when it runs. im not going to look into it any further

[latest.log](https://github.com/The-Fireplace-Minecraft-Mods/Home-Camp/files/10072517/latest.log)
[modlist.txt](https://github.com/The-Fireplace-Minecraft-Mods/Home-Camp/files/10072519/modlist.txt)
